export const SET_BUILDING = 'SET_BUILDING'
export const SET_HEIGHT = 'SET_HEIGHT'
export const SET_MATERIAL = 'SET_MATERIAL'
export const SET_SIZEX = 'SET_SIZEX'
export const SET_SIZEY = 'SET_SIZEY'

export const GET_RESULT_FETCH_START = 'GET_RESULT_FETCH_START'
export const GET_RESULT_FETCH_SUCCESS = 'GET_RESULT_FETCH_SUCCESS'
export const GET_RESULT_FETCH_ERROR = 'GET_RESULT_FETCH_ERROR'

export const RESET_CALCULATOR = 'RESET_CALCULATOR'
